apt-get install acl
apt-get install acpi
apt-get install acpi-support
apt-get install acpid
apt-get install adduser
apt-get install alacarte
apt-get install alsa-base
apt-get install alsa-utils
apt-get install anacron
apt-get install apmd
apt-get install app-install-data-partner
apt-get install apport
apt-get install apport-gtk
apt-get install apt
apt-get install apt-transport-https
apt-get install apt-utils
apt-get install apt-xapian-index
apt-get install aptitude
apt-get install aptoncd
apt-get install aspell
apt-get install aspell-en
apt-get install at
apt-get install at-spi
apt-get install autoconf
apt-get install automake
apt-get install autotools-dev
apt-get install avahi-autoipd
apt-get install avahi-daemon
apt-get install avahi-utils
apt-get install avifile-mad-plugin
apt-get install avifile-vorbis-plugin
apt-get install avifile-win32-plugin
apt-get install base-files
apt-get install base-passwd
apt-get install bash
apt-get install bash-completion
apt-get install bc
apt-get install bind9-host
apt-get install binfmt-support
apt-get install binutils
apt-get install binutils-static
apt-get install bison
apt-get install bluetooth
apt-get install bluez
apt-get install bluez-alsa
apt-get install bluez-cups
apt-get install bluez-gnome
apt-get install bluez-gstreamer
apt-get install bluez-utils
apt-get install bogofilter
apt-get install bogofilter-bdb
apt-get install bogofilter-common
apt-get install brasero
apt-get install brltty
apt-get install brltty-x11
apt-get install bsdmainutils
apt-get install bsdutils
apt-get install bsh
apt-get install build-essential
apt-get install busybox-initramfs
apt-get install bzip2
apt-get install ca-certificates
apt-get install cabextract
apt-get install calendar-google-provider
apt-get install calendar-timezones
apt-get install capplets-data
apt-get install cdparanoia
apt-get install check
apt-get install checkbox
apt-get install cli-common
apt-get install cmake
apt-get install comerr-dev
apt-get install command-not-found
apt-get install command-not-found-data
apt-get install compiz
apt-get install compiz-check
apt-get install compiz-core
apt-get install compiz-fusion-plugins-extra
apt-get install compiz-fusion-plugins-main
apt-get install compiz-gnome
apt-get install compiz-plugins
apt-get install compiz-wrapper
apt-get install compizconfig-backend-gconf
apt-get install compizconfig-settings-manager
apt-get install computer-janitor
apt-get install computer-janitor-gtk
apt-get install console-setup
apt-get install console-terminus
apt-get install consolekit
apt-get install contact-lookup-applet
apt-get install coreutils
apt-get install cowsay
apt-get install cpio
apt-get install cpp
apt-get install cpp-4.3
apt-get install cron
apt-get install cups
apt-get install cups-bsd
apt-get install cups-client
apt-get install cups-common
apt-get install cups-driver-gutenprint
apt-get install cups-pdf
apt-get install cupsddk
apt-get install cupsddk-drivers
apt-get install dash
apt-get install dbus
apt-get install dbus-x11
apt-get install dc
apt-get install dcraw
apt-get install debconf
apt-get install debconf-i18n
apt-get install debhelper
apt-get install debianutils
apt-get install defoma
apt-get install deskbar-applet
apt-get install desktop-file-utils
apt-get install dhcp3-client
apt-get install dhcp3-common
apt-get install dictionaries-common
apt-get install diff
apt-get install dkms
apt-get install dmidecode
apt-get install dmsetup
apt-get install dmz-cursor-theme
apt-get install dnsmasq-base
apt-get install dnsutils
apt-get install doc-base
apt-get install docbook-xml
apt-get install dontzap
apt-get install dosfstools
apt-get install dpkg
apt-get install dpkg-dev
apt-get install dvd+rw-tools
apt-get install e2fslibs
apt-get install e2fsprogs
apt-get install ecryptfs-utils
apt-get install ed
apt-get install eject
apt-get install envyng-core
apt-get install envyng-gtk
apt-get install eog
apt-get install esound-clients
apt-get install esound-common
apt-get install espeak-data
apt-get install ethtool
apt-get install evince
apt-get install evolution-data-server
apt-get install evolution-data-server-common
apt-get install evolution-documentation-en
apt-get install fakeroot
apt-get install fast-user-switch-applet
apt-get install ffmpeg
apt-get install fglrx-modaliases
apt-get install file
apt-get install file-roller
apt-get install findutils
apt-get install finger
apt-get install firefox
apt-get install firefox-3.0
apt-get install firefox-3.0-branding
apt-get install firefox-3.0-gnome-support
apt-get install firefox-gnome-support
apt-get install flashplugin-installer
apt-get install flashplugin-nonfree
apt-get install flegita
apt-get install flex
apt-get install fontconfig
apt-get install fontconfig-config
apt-get install foo2zjs
apt-get install foomatic-db
apt-get install foomatic-db-engine
apt-get install foomatic-db-hpijs
apt-get install foomatic-filters
apt-get install fortune-mod
apt-get install fortunes-min
apt-get install freeglut3
apt-get install friendly-recovery
apt-get install ftp
apt-get install fuse-utils
apt-get install g++
apt-get install g++-4.3
apt-get install gamin
apt-get install gawk
apt-get install gcalctool
apt-get install gcc
apt-get install gcc-4.3
apt-get install gcc-4.3-base
apt-get install gccxml
apt-get install gconf-editor
apt-get install gconf2
apt-get install gconf2-common
apt-get install gdb
apt-get install gdebi
apt-get install gdebi-core
apt-get install gdm
apt-get install gecko-mediaplayer
apt-get install gedit
apt-get install gedit-common
apt-get install genisoimage
apt-get install gettext
apt-get install gettext-base
apt-get install ghostscript
apt-get install ghostscript-x
apt-get install gimp
apt-get install gimp-data
apt-get install gimp-help-common
apt-get install gimp-help-en
apt-get install giver
apt-get install gksu
apt-get install gnome-about
apt-get install gnome-applets
apt-get install gnome-applets-data
apt-get install gnome-codec-install
apt-get install gnome-control-center
apt-get install gnome-desktop-data
apt-get install gnome-do
apt-get install gnome-doc-utils
apt-get install gnome-icon-theme
apt-get install gnome-keyring
apt-get install gnome-mag
apt-get install gnome-media
apt-get install gnome-media-common
apt-get install gnome-menus
apt-get install gnome-mime-data
apt-get install gnome-mount
apt-get install gnome-mplayer
apt-get install gnome-nettool
apt-get install gnome-panel
apt-get install gnome-panel-data
apt-get install gnome-pilot
apt-get install gnome-pilot-conduits
apt-get install gnome-power-manager
apt-get install gnome-screensaver
apt-get install gnome-session
apt-get install gnome-session-canberra
apt-get install gnome-settings-daemon
apt-get install gnome-system-monitor
apt-get install gnome-system-tools
apt-get install gnome-terminal
apt-get install gnome-terminal-data
apt-get install gnome-themes-selected
apt-get install gnome-utils
apt-get install gnupg
apt-get install gpac
apt-get install gparted
apt-get install gpgv
apt-get install grep
apt-get install groff-base
apt-get install grub-common
apt-get install grub-gfxboot
apt-get install gsfonts
apt-get install gsfonts-x11
apt-get install gstreamer-tools
apt-get install gstreamer0.10-alsa
apt-get install gstreamer0.10-doc
apt-get install gstreamer0.10-esd
apt-get install gstreamer0.10-ffmpeg
apt-get install gstreamer0.10-fluendo-mp3
apt-get install gstreamer0.10-gnomevfs
apt-get install gstreamer0.10-gnonlin-doc
apt-get install gstreamer0.10-pitfdll
apt-get install gstreamer0.10-plugins-bad
apt-get install gstreamer0.10-plugins-bad-multiverse
apt-get install gstreamer0.10-plugins-base
apt-get install gstreamer0.10-plugins-base-apps
apt-get install gstreamer0.10-plugins-farsight
apt-get install gstreamer0.10-plugins-good
apt-get install gstreamer0.10-plugins-ugly
apt-get install gstreamer0.10-plugins-ugly-multiverse
apt-get install gstreamer0.10-pulseaudio
apt-get install gstreamer0.10-schroedinger
apt-get install gstreamer0.10-sdl
apt-get install gstreamer0.10-tools
apt-get install gstreamer0.10-x
apt-get install gtk2-engines
apt-get install gtk2-engines-aurora
apt-get install gtk2-engines-candido
apt-get install gtk2-engines-murrine
apt-get install gtk2-engines-pixbuf
apt-get install gtk2-engines-ubuntulooks
apt-get install gucharmap
apt-get install gufw
apt-get install guile-1.8-libs
apt-get install gvfs
apt-get install gvfs-backends
apt-get install gvfs-bin
apt-get install gvfs-fuse
apt-get install gzip
apt-get install hal
apt-get install hal-cups-utils
apt-get install hal-info
apt-get install hdparm
apt-get install hicolor-icon-theme
apt-get install hostname
apt-get install hotkey-setup
apt-get install hpijs
apt-get install hplip
apt-get install hplip-data
apt-get install html2text
apt-get install human-icon-theme
apt-get install hunspell-en-us
apt-get install ifupdown
apt-get install im-switch
apt-get install imagemagick
apt-get install imagemagick-doc
apt-get install indicator-applet
apt-get install indicator-messages
apt-get install info
apt-get install initramfs-tools
apt-get install initscripts
apt-get install inputattach
apt-get install intltool
apt-get install intltool-debian
apt-get install inxi
apt-get install iproute
apt-get install iptables
apt-get install iputils-arping
apt-get install iputils-ping
apt-get install iputils-tracepath
apt-get install iso-codes
apt-get install java-common
apt-get install jfsutils
apt-get install jockey-common
apt-get install jockey-gtk
apt-get install kbd
apt-get install keyutils
apt-get install klibc-utils
apt-get install klogd
apt-get install language-pack-en
apt-get install language-pack-en-base
apt-get install language-pack-gnome-en
apt-get install language-pack-gnome-en-base
apt-get install language-selector
apt-get install language-selector-common
apt-get install language-support-en
apt-get install language-support-translations-en
apt-get install language-support-writing-en
apt-get install laptop-detect
apt-get install laptop-mode-tools
apt-get install launchpad-integration
apt-get install less
apt-get install lftp
apt-get install liba52-0.7.4
apt-get install libaa1
apt-get install libaa1-dev
apt-get install libacl1
apt-get install libamrnb3
apt-get install libamrwb3
apt-get install libao2
apt-get install libapm1
apt-get install libapparmor-perl
apt-get install libapparmor1
apt-get install libapr1
apt-get install libaprutil1
apt-get install libarchive1
apt-get install libart-2.0-2
apt-get install libart2.24-cil
apt-get install libasound2
apt-get install libasound2-dev
apt-get install libasound2-plugins
apt-get install libaspell15
apt-get install libass1
apt-get install libatk1.0-0
apt-get install libatk1.0-data
apt-get install libatk1.0-dev
apt-get install libatm1
apt-get install libatspi1.0-0
apt-get install libattr1
apt-get install libaudio-dev
apt-get install libaudio2
apt-get install libaudiofile-dev
apt-get install libaudiofile0
apt-get install libavahi-client3
apt-get install libavahi-common-data
apt-get install libavahi-common3
apt-get install libavahi-compat-libdnssd1
apt-get install libavahi-core5
apt-get install libavahi-glib1
apt-get install libavahi-gobject0
apt-get install libavahi1.0-cil
apt-get install libavc1394-0
apt-get install libavcodec-unstripped-52
apt-get install libavcodec52
apt-get install libavdevice52
apt-get install libavfilter0
apt-get install libavformat-unstripped-52
apt-get install libavformat52
apt-get install libavifile-0.7c2
apt-get install libavutil-unstripped-49
apt-get install libavutil49
apt-get install libbabl-0.0-0
apt-get install libbeagle1
apt-get install libbind9-40
apt-get install libblkid1
apt-get install libbluetooth3
apt-get install libbonobo2-0
apt-get install libbonobo2-common
apt-get install libbonoboui2-0
apt-get install libbonoboui2-common
apt-get install libboost-date-time1.35-dev
apt-get install libboost-date-time1.35.0
apt-get install libboost-filesystem1.35-dev
apt-get install libboost-filesystem1.35.0
apt-get install libboost-graph1.35-dev
apt-get install libboost-graph1.35.0
apt-get install libboost-iostreams1.35-dev
apt-get install libboost-iostreams1.35.0
apt-get install libboost-program-options1.35-dev
apt-get install libboost-program-options1.35.0
apt-get install libboost-python1.35-dev
apt-get install libboost-python1.35.0
apt-get install libboost-regex1.35-dev
apt-get install libboost-regex1.35.0
apt-get install libboost-serialization1.35-dev
apt-get install libboost-serialization1.35.0
apt-get install libboost-signals1.35-dev
apt-get install libboost-signals1.35.0
apt-get install libboost-system1.35-dev
apt-get install libboost-system1.35.0
apt-get install libboost-test1.35-dev
apt-get install libboost-test1.35.0
apt-get install libboost-thread1.35-dev
apt-get install libboost-thread1.35.0
apt-get install libboost-wave1.35-dev
apt-get install libboost-wave1.35.0
apt-get install libboost1.35-dev
apt-get install libboost1.35-doc
apt-get install libbrasero-media0
apt-get install libbrlapi0.5
apt-get install libbz2-1.0
apt-get install libc6
apt-get install libc6-dev
apt-get install libc6-i686
apt-get install libcaca-dev
apt-get install libcaca0
apt-get install libcairo-perl
apt-get install libcairo2
apt-get install libcairo2-dev
apt-get install libcairomm-1.0-1
apt-get install libcamel1.2-14
apt-get install libcanberra-gtk-module
apt-get install libcanberra-gtk0
apt-get install libcanberra0
apt-get install libcap2
apt-get install libcdaudio1
apt-get install libcdio-cdda0
apt-get install libcdio-paranoia0
apt-get install libcdio7
apt-get install libcdparanoia0
apt-get install libcelt0
apt-get install libck-connector0
apt-get install libclass-accessor-perl
apt-get install libcolamd-3.2.0
apt-get install libcomerr2
apt-get install libcompizconfig0
apt-get install libcompress-raw-zlib-perl
apt-get install libcompress-zlib-perl
apt-get install libcroco3
apt-get install libcryptui0
apt-get install libcups2
apt-get install libcupsimage2
apt-get install libcurl3-gnutls
apt-get install libcwidget3
apt-get install libdaemon0
apt-get install libdatrie0
apt-get install libdb4.6
apt-get install libdb4.7
apt-get install libdbus-1-3
apt-get install libdbus-1-dev
apt-get install libdbus-glib-1-2
apt-get install libdc1394-22
apt-get install libdca0
apt-get install libdebconfclient0
apt-get install libdecoration0
apt-get install libdevmapper1.02.1
apt-get install libdirectfb-1.0-0
apt-get install libdirectfb-dev
apt-get install libdirectfb-extra
apt-get install libdiscid0
apt-get install libdjvulibre-text
apt-get install libdjvulibre21
apt-get install libdmx1
apt-get install libdns45
apt-get install libdrm-intel1
apt-get install libdrm2
apt-get install libdv4
apt-get install libdvbpsi4
apt-get install libdvdcss2
apt-get install libdvdnav4
apt-get install libdvdread4
apt-get install libebackend1.2-0
apt-get install libebml0
apt-get install libebook1.2-9
apt-get install libecal1.2-7
apt-get install libecryptfs0
apt-get install libedata-book1.2-2
apt-get install libedata-cal1.2-6
apt-get install libedataserver1.2-11
apt-get install libedataserverui1.2-8
apt-get install libedit2
apt-get install libegroupwise1.2-13
apt-get install libelf1
apt-get install libenca-dev
apt-get install libenca0
apt-get install libenchant1c2a
apt-get install libept0
apt-get install libesd-alsa0
apt-get install libesd0-dev
apt-get install libespeak1
apt-get install libevdocument1
apt-get install libevview1
apt-get install libexempi3
apt-get install libexif12
apt-get install libexpat1
apt-get install libexpat1-dev
apt-get install libfaac-dev
apt-get install libfaac0
apt-get install libfaad-dev
apt-get install libfaad0
apt-get install libffado0
apt-get install libffi5
apt-get install libfftw3-3
apt-get install libflac8
apt-get install libfont-afm-perl
apt-get install libfontconfig1
apt-get install libfontconfig1-dev
apt-get install libfontenc1
apt-get install libfreebob0
apt-get install libfreetype6
apt-get install libfreetype6-dev
apt-get install libfreezethaw-perl
apt-get install libfribidi0
apt-get install libfs6
apt-get install libfuse2
apt-get install libgadu3
apt-get install libgail-common
apt-get install libgail-gnome-module
apt-get install libgail18
apt-get install libgamin0
apt-get install libgc1c2
apt-get install libgcc1
apt-get install libgconf2-4
apt-get install libgconf2-dev
apt-get install libgconf2.24-cil
apt-get install libgconfmm-2.6-1c2
apt-get install libgcr0
apt-get install libgcrypt11
apt-get install libgd2-noxpm
apt-get install libgdata-google1.2-1
apt-get install libgdata1.2-1
apt-get install libgdbm3
apt-get install libgdict-1.0-6
apt-get install libgdiplus
apt-get install libgegl-0.0-0
apt-get install libggi-target-x
apt-get install libggi2
apt-get install libgif4
apt-get install libgii1
apt-get install libgii1-target-x
apt-get install libgimp2.0
apt-get install libgksu2-0
apt-get install libgl1-mesa-dev
apt-get install libgl1-mesa-dri
apt-get install libgl1-mesa-glx
apt-get install libglade2-0
apt-get install libglade2-dev
apt-get install libglade2.0-cil
apt-get install libglademm-2.4-1c2a
apt-get install libglew1.5
apt-get install libglib-perl
apt-get install libglib1.2ldbl
apt-get install libglib2-ruby
apt-get install libglib2-ruby1.8
apt-get install libglib2.0-0
apt-get install libglib2.0-cil
apt-get install libglib2.0-data
apt-get install libglib2.0-dev
apt-get install libglibmm-2.4-1c2a
apt-get install libglitz-glx1
apt-get install libglitz1
apt-get install libglu1-mesa
apt-get install libglu1-mesa-dev
apt-get install libgmime-2.0-2a
apt-get install libgmime2.2a-cil
apt-get install libgmp3c2
apt-get install libgmyth0
apt-get install libgnome-desktop-2-11
apt-get install libgnome-keyring0
apt-get install libgnome-keyring1.0-cil
apt-get install libgnome-mag2
apt-get install libgnome-media0
apt-get install libgnome-menu2
apt-get install libgnome-pilot2
apt-get install libgnome-speech7
apt-get install libgnome-vfs2.24-cil
apt-get install libgnome-window-settings1
apt-get install libgnome2-0
apt-get install libgnome2-canvas-perl
apt-get install libgnome2-common
apt-get install libgnome2-perl
apt-get install libgnome2-vfs-perl
apt-get install libgnome2.24-cil
apt-get install libgnomecanvas2-0
apt-get install libgnomecanvas2-common
apt-get install libgnomecups1.0-1
apt-get install libgnomedesktop2.20-cil
apt-get install libgnomekbd-common
apt-get install libgnomekbd3
apt-get install libgnomekbdui3
apt-get install libgnomepanel2.24-cil
apt-get install libgnomeprint2.2-0
apt-get install libgnomeprint2.2-data
apt-get install libgnomeprintui2.2-0
apt-get install libgnomeprintui2.2-common
apt-get install libgnomescan-common
apt-get install libgnomescan0
apt-get install libgnomescanui-common
apt-get install libgnomescanui0
apt-get install libgnomeui-0
apt-get install libgnomeui-common
apt-get install libgnomevfs2-0
apt-get install libgnomevfs2-bin
apt-get install libgnomevfs2-common
apt-get install libgnomevfs2-extra
apt-get install libgnutls26
apt-get install libgomp1
apt-get install libgp11-0
apt-get install libgpac0.4.4
apt-get install libgpg-error0
apt-get install libgpgme11
apt-get install libgphoto2-2
apt-get install libgphoto2-port0
apt-get install libgpm2
apt-get install libgpod-common
apt-get install libgpod4
apt-get install libgraphviz4
apt-get install libgs8
apt-get install libgsf-1-114
apt-get install libgsf-1-common
apt-get install libgsl0ldbl
apt-get install libgsm1
apt-get install libgstreamer-plugins-base0.10-0
apt-get install libgstreamer0.10-0
apt-get install libgstreamer0.10-dev
apt-get install libgstreamer0.10-ruby1.8
apt-get install libgtk-vnc-1.0-0
apt-get install libgtk1.2
apt-get install libgtk1.2-common
apt-get install libgtk2-perl
apt-get install libgtk2.0-0
apt-get install libgtk2.0-bin
apt-get install libgtk2.0-cil
apt-get install libgtk2.0-common
apt-get install libgtk2.0-dev
apt-get install libgtkhtml-editor-common
apt-get install libgtkhtml-editor0
apt-get install libgtkhtml2-0
apt-get install libgtkhtml3.14-19
apt-get install libgtkmm-2.4-1c2a
apt-get install libgtksourceview-common
apt-get install libgtksourceview1.0-0
apt-get install libgtksourceview2.0-0
apt-get install libgtksourceview2.0-common
apt-get install libgtkspell0
apt-get install libgtop2-7
apt-get install libgtop2-common
apt-get install libgucharmap7
apt-get install libgutenprint2
apt-get install libgvfscommon0
apt-get install libgweather-common
apt-get install libgweather1
apt-get install libhal-storage1
apt-get install libhal1
apt-get install libhesiod0
apt-get install libhsqldb-java
apt-get install libhtml-format-perl
apt-get install libhtml-parser-perl
apt-get install libhtml-tagset-perl
apt-get install libhtml-tree-perl
apt-get install libhunspell-1.2-0
apt-get install libhyphen0
apt-get install libical0
apt-get install libice-dev
apt-get install libice6
apt-get install libicu-dev
apt-get install libicu38
apt-get install libid3tag0
apt-get install libidl-dev
apt-get install libidl0
apt-get install libidn11
apt-get install libiec61883-0
apt-get install libiec61883-dev
apt-get install libieee1284-3
apt-get install libijs-0.35
apt-get install libilmbase6
apt-get install libindicate1
apt-get install libio-compress-base-perl
apt-get install libio-compress-zlib-perl
apt-get install libio-string-perl
apt-get install libiptcdata0
apt-get install libisc45
apt-get install libisccc40
apt-get install libisccfg40
apt-get install libiso9660-5
apt-get install libiw29
apt-get install libjack0
apt-get install libjasper1
apt-get install libjinglebase0.3-0
apt-get install libjinglep2p0.3-0
apt-get install libjinglexmllite0.3-0
apt-get install libjinglexmpp0.3-0
apt-get install libjline-java
apt-get install libjpeg62
apt-get install libjpeg62-dev
apt-get install libkadm55
apt-get install libkeyutils1
apt-get install libklibc
apt-get install libkpathsea4
apt-get install libkrb5-dev
apt-get install libkrb53
apt-get install liblaunchpad-integration1
apt-get install liblcms1
apt-get install liblcms1-dev
apt-get install libldap-2.4-2
apt-get install liblircclient0
apt-get install liblocale-gettext-perl
apt-get install liblockfile1
apt-get install liblpint-bonobo0
apt-get install liblrdf0
apt-get install libltdl7
apt-get install liblua5.1-0
apt-get install liblwres40
apt-get install liblzo2-2
apt-get install libmad0
apt-get install libmad0-dev
apt-get install libmagic1
apt-get install libmagickcore1
apt-get install libmagickwand1
apt-get install libmail-sendmail-perl
apt-get install libmailtools-perl
apt-get install libmatroska0
apt-get install libmbca0
apt-get install libmeanwhile1
apt-get install libmetacity0
apt-get install libmjpegtools-1.9
apt-get install libmldbm-perl
apt-get install libmms0
apt-get install libmng-dev
apt-get install libmng1
apt-get install libmodplug0c2
apt-get install libmono-addins-gui0.2-cil
apt-get install libmono-addins0.2-cil
apt-get install libmono-cairo2.0-cil
apt-get install libmono-corlib2.0-cil
apt-get install libmono-data-tds2.0-cil
apt-get install libmono-data2.0-cil
apt-get install libmono-getoptions2.0-cil
apt-get install libmono-i18n2.0-cil
apt-get install libmono-posix2.0-cil
apt-get install libmono-security2.0-cil
apt-get install libmono-sharpzip2.84-cil
apt-get install libmono-system-data2.0-cil
apt-get install libmono-system2.0-cil
apt-get install libmono0
apt-get install libmoon
apt-get install libmp3lame-dev
apt-get install libmp3lame0
apt-get install libmp4v2-0
apt-get install libmp4v2-dev
apt-get install libmpcdec3
apt-get install libmpeg2-4
apt-get install libmpeg2-4-dev
apt-get install libmpeg3-1
apt-get install libmpeg4ip-0
apt-get install libmpeg4ip-dev
apt-get install libmpfr1ldbl
apt-get install libmtp8
apt-get install libmusicbrainz3-6
apt-get install libmusicbrainz4c2a
apt-get install libmysqlclient15off
apt-get install libnautilus-burn4
apt-get install libnautilus-extension1
apt-get install libncurses5
apt-get install libncurses5-dev
apt-get install libncursesw5
apt-get install libndesk-dbus-glib1.0-cil
apt-get install libndesk-dbus1.0-cil
apt-get install libneon27
apt-get install libneon27-gnutls
apt-get install libnet-dbus-perl
apt-get install libnewt0.52
apt-get install libnl1
apt-get install libnm-glib0
apt-get install libnm-util1
apt-get install libnotify-bin
apt-get install libnotify0.4-cil
apt-get install libnotify1
apt-get install libnspr4-0d
apt-get install libnss-mdns
apt-get install libnss3-1d
apt-get install libntfs-3g49
apt-get install libntfs10
apt-get install libofa0
apt-get install libogg-dev
apt-get install libogg0
apt-get install libogmrip-dev
apt-get install libogmrip0
apt-get install liboil0.3
apt-get install liboobs-1-4
apt-get install libopal3.6.1
apt-get install libopenal1
apt-get install libopenexr6
apt-get install libopenobex1
apt-get install libopenspc0
apt-get install liborbit2
apt-get install liborbit2-dev
apt-get install libotr2
apt-get install libpam-ck-connector
apt-get install libpam-gnome-keyring
apt-get install libpam-modules
apt-get install libpam-runtime
apt-get install libpam0g
apt-get install libpanel-applet2-0
apt-get install libpango1.0-0
apt-get install libpango1.0-common
apt-get install libpango1.0-dev
apt-get install libpangomm-1.4-1
apt-get install libpaper-utils
apt-get install libpaper1
apt-get install libparse-debianchangelog-perl
apt-get install libparted1.8-10
apt-get install libpcap0.8
apt-get install libpci3
apt-get install libpciaccess0
apt-get install libpcre3
apt-get install libpcsclite1
apt-get install libperl5.10
apt-get install libphonon4
apt-get install libpisock9
apt-get install libpisync1
apt-get install libpixman-1-0
apt-get install libpixman-1-dev
apt-get install libpng12-0
apt-get install libpng12-dev
apt-get install libpoco-dev
apt-get install libpococrypto6
apt-get install libpocodata6
apt-get install libpocofoundation6
apt-get install libpocomysql6
apt-get install libpoconet6
apt-get install libpoconetssl6
apt-get install libpocoodbc6
apt-get install libpocosqlite6
apt-get install libpocoutil6
apt-get install libpocoxml6
apt-get install libpocozip6
apt-get install libpolkit-dbus2
apt-get install libpolkit-gnome0
apt-get install libpolkit-grant2
apt-get install libpolkit2
apt-get install libpoppler-glib4
apt-get install libpoppler4
apt-get install libpopt-dev
apt-get install libpopt0
apt-get install libportaudio2
apt-get install libpostproc51
apt-get install libpq-dev
apt-get install libpq5
apt-get install libprotobuf3
apt-get install libproxy0
apt-get install libpt2.6.1
apt-get install libpt2.6.1-plugins-alsa
apt-get install libpt2.6.1-plugins-v4l2
apt-get install libpth20
apt-get install libpthread-stubs0
apt-get install libpthread-stubs0-dev
apt-get install libpulse-browse0
apt-get install libpulse-mainloop-glib0
apt-get install libpulse0
apt-get install libpulsecore9
apt-get install libpurple-bin
apt-get install libpurple0
apt-get install libpython2.6
apt-get install libqt4-assistant
apt-get install libqt4-dbus
apt-get install libqt4-designer
apt-get install libqt4-dev
apt-get install libqt4-help
apt-get install libqt4-network
apt-get install libqt4-opengl
apt-get install libqt4-opengl-dev
apt-get install libqt4-qt3support
apt-get install libqt4-script
apt-get install libqt4-scripttools
apt-get install libqt4-sql
apt-get install libqt4-sql-mysql
apt-get install libqt4-svg
apt-get install libqt4-test
apt-get install libqt4-webkit
apt-get install libqt4-xml
apt-get install libqt4-xmlpatterns
apt-get install libqtcore4
apt-get install libqtgui4
apt-get install libquicktime1
apt-get install libraptor1
apt-get install librarian0
apt-get install libraw1394-8
apt-get install libraw1394-dev
apt-get install libreadline5
apt-get install librecode0
apt-get install librsvg2-2
apt-get install librsvg2-2.18-cil
apt-get install librsvg2-common
apt-get install libruby1.8
apt-get install libsamplerate0
apt-get install libsane
apt-get install libsasl2-2
apt-get install libsasl2-modules
apt-get install libschroedinger-1.0-0
apt-get install libscim8c2a
apt-get install libsdl-image1.2
apt-get install libsdl1.2-dev
apt-get install libsdl1.2debian
apt-get install libsdl1.2debian-alsa
apt-get install libselinux1
apt-get install libsensors3
apt-get install libsepol1
apt-get install libservlet2.4-java
apt-get install libsexy2
apt-get install libsgutils1
apt-get install libshout3
apt-get install libsidplay1
apt-get install libsigc++-2.0-0c2a
apt-get install libsilc-1.1-2
apt-get install libslang2
apt-get install libslang2-dev
apt-get install libslp1
apt-get install libsm-dev
apt-get install libsm6
apt-get install libsmbclient
apt-get install libsmbios2
apt-get install libsmpeg-dev
apt-get install libsmpeg0
apt-get install libsndfile1
apt-get install libsnmp-base
apt-get install libsnmp15
apt-get install libsoundtouch1c2
apt-get install libsoup-gnome2.4-1
apt-get install libsoup2.4-1
apt-get install libsox-fmt-alsa
apt-get install libsox-fmt-base
apt-get install libsox-fmt-mp3
apt-get install libsox1
apt-get install libspectre1
apt-get install libspeex1
apt-get install libspeexdsp1
apt-get install libsqlite0
apt-get install libsqlite0-dev
apt-get install libsqlite3-0
apt-get install libss2
apt-get install libssl-dev
apt-get install libssl0.9.8
apt-get install libstartup-notification0
apt-get install libstdc++5
apt-get install libstdc++6
apt-get install libstdc++6-4.3-dev
apt-get install libstlport4.6ldbl
apt-get install libsvga1
apt-get install libsvn1
apt-get install libswscale0
apt-get install libsys-hostname-long-perl
apt-get install libsysfs-dev
apt-get install libsysfs2
apt-get install libtag1c2a
apt-get install libtalloc1
apt-get install libtar
apt-get install libtasn1-3
apt-get install libtdb1
apt-get install libtext-charwidth-perl
apt-get install libtext-iconv-perl
apt-get install libtext-wrapi18n-perl
apt-get install libthai-data
apt-get install libthai0
apt-get install libtheora-dev
apt-get install libtheora0
apt-get install libtie-ixhash-perl
apt-get install libtiff4
apt-get install libtimedate-perl
apt-get install libtotem-plparser12
apt-get install libtrackerclient0
apt-get install libts-0.0-0
apt-get install libtsmux-dev
apt-get install libtsmux0
apt-get install libtwolame-dev
apt-get install libtwolame0
apt-get install libudev0
apt-get install libunique-1.0-0
apt-get install libunshield0
apt-get install liburi-perl
apt-get install libusb-0.1-4
apt-get install libusplash0
apt-get install libuuid-perl
apt-get install libuuid1
apt-get install libv4l-0
apt-get install libvcdinfo0
apt-get install libvisual-0.4-0
apt-get install libvisual-0.4-plugins
apt-get install libvlc-dev
apt-get install libvlc2
apt-get install libvlccore-dev
apt-get install libvlccore0
apt-get install libvolume-id1
apt-get install libvorbis-dev
apt-get install libvorbis0a
apt-get install libvorbisenc2
apt-get install libvorbisfile3
apt-get install libvte-common
apt-get install libvte9
apt-get install libwavpack1
apt-get install libwbclient0
apt-get install libwildmidi0
apt-get install libwmf0.2-7
apt-get install libwmf0.2-7-gtk
apt-get install libwnck-common
apt-get install libwnck2.20-cil
apt-get install libwnck22
apt-get install libwpd8c2a
apt-get install libwpg-0.1-1
apt-get install libwps-0.1-1
apt-get install libwrap0
apt-get install libwww-perl
apt-get install libwxbase2.6-0
apt-get install libwxgtk2.6-0
apt-get install libx11-6
apt-get install libx11-data
apt-get install libx11-dev
apt-get install libx264-65
apt-get install libx264-dev
apt-get install libx86-1
apt-get install libxapian15
apt-get install libxau-dev
apt-get install libxau6
apt-get install libxaw7
apt-get install libxcb-render-util0
apt-get install libxcb-render-util0-dev
apt-get install libxcb-render0
apt-get install libxcb-render0-dev
apt-get install libxcb-shape0
apt-get install libxcb-shm0
apt-get install libxcb-xv0
apt-get install libxcb-xv0-dbg
apt-get install libxcb1
apt-get install libxcb1-dev
apt-get install libxcomposite-dev
apt-get install libxcomposite1
apt-get install libxcursor-dev
apt-get install libxcursor1
apt-get install libxdamage-dev
apt-get install libxdamage1
apt-get install libxdmcp-dev
apt-get install libxdmcp6
apt-get install libxext-dev
apt-get install libxext6
apt-get install libxfixes-dev
apt-get install libxfixes3
apt-get install libxfont1
apt-get install libxft-dev
apt-get install libxft2
apt-get install libxi-dev
apt-get install libxi6
apt-get install libxine-dev
apt-get install libxine1
apt-get install libxine1-bin
apt-get install libxine1-console
apt-get install libxine1-ffmpeg
apt-get install libxine1-gnome
apt-get install libxine1-misc-plugins
apt-get install libxine1-x
apt-get install libxine1-xvdr
apt-get install libxineliboutput-sxfe
apt-get install libxinerama-dev
apt-get install libxinerama1
apt-get install libxkbfile1
apt-get install libxklavier12
apt-get install libxml++2.6-2
apt-get install libxml-parser-perl
apt-get install libxml-twig-perl
apt-get install libxml-xpath-perl
apt-get install libxml2
apt-get install libxml2-dev
apt-get install libxml2-utils
apt-get install libxmu-dev
apt-get install libxmu-headers
apt-get install libxmu6
apt-get install libxmuu1
apt-get install libxp6
apt-get install libxpm4
apt-get install libxrandr-dev
apt-get install libxrandr2
apt-get install libxrender-dev
apt-get install libxrender1
apt-get install libxres1
apt-get install libxslt1.1
apt-get install libxss1
apt-get install libxt-dev
apt-get install libxt6
apt-get install libxtrap6
apt-get install libxtst6
apt-get install libxv-dev
apt-get install libxv1
apt-get install libxvidcore4
apt-get install libxvidcore4-dev
apt-get install libxvmc-dev
apt-get install libxvmc1
apt-get install libxxf86dga1
apt-get install libxxf86misc1
apt-get install libxxf86vm-dev
apt-get install libxxf86vm1
apt-get install libzephyr3
apt-get install lightning-extension
apt-get install linux-firmware
apt-get install linux-generic
apt-get install linux-headers-2.6.28-11
apt-get install linux-headers-2.6.28-11-generic
apt-get install linux-headers-generic
apt-get install linux-image-2.6.28-11-generic
apt-get install linux-image-generic
apt-get install linux-libc-dev
apt-get install linux-restricted-modules-2.6.28-11-generic
apt-get install linux-restricted-modules-common
apt-get install linux-restricted-modules-generic
apt-get install linux-sound-base
apt-get install linuxmint-keyring
apt-get install lirc
apt-get install localechooser-data
apt-get install locales
apt-get install lockfile-progs
apt-get install login
apt-get install logrotate
apt-get install lp-solve
apt-get install lsb-base
apt-get install lsb-release
apt-get install lshw
apt-get install lsof
apt-get install ltrace
apt-get install lzma
apt-get install m4
apt-get install make
apt-get install makedev
apt-get install man-db
apt-get install manpages
apt-get install mawk
apt-get install medibuntu-keyring
apt-get install memtest86+
apt-get install mesa-common-dev
apt-get install mesa-utils
apt-get install metacity
apt-get install metacity-common
apt-get install mime-support
apt-get install min12xxw
apt-get install mint-artwork-gnome
apt-get install mint-info-main
apt-get install mint-meta-gnome
apt-get install mint-meta-main
apt-get install mint-search-addon
apt-get install mintbackup
apt-get install mintdesktop
apt-get install mintinstall
apt-get install mintmenu
apt-get install mintnanny
apt-get install mintsystem
apt-get install mintupdate
apt-get install mintupload
apt-get install mintwelcome
apt-get install mintwifi
apt-get install mktemp
apt-get install mlocate
apt-get install mobile-broadband-provider-info
apt-get install module-init-tools
apt-get install mono-2.0-gac
apt-get install mono-2.0-runtime
apt-get install mono-common
apt-get install mono-gac
apt-get install mono-jit
apt-get install mono-runtime
apt-get install moonlight-plugin-core
apt-get install moonlight-plugin-mozilla
apt-get install mount
apt-get install mousetweaks
apt-get install mozilla-thunderbird
apt-get install mpeg2dec
apt-get install mpeg3-utils
apt-get install mpeg4ip-server
apt-get install mpeg4ip-utils
apt-get install mpegdemux
apt-get install mplayer
apt-get install mplayer-skins
apt-get install mscompress
apt-get install mtools
apt-get install mtr-tiny
apt-get install myspell-en-au
apt-get install myspell-en-gb
apt-get install myspell-en-za
apt-get install mysql-common
apt-get install nano
apt-get install nautilus
apt-get install nautilus-actions
apt-get install nautilus-data
apt-get install nautilus-open-terminal
apt-get install nautilus-sendto
apt-get install nautilus-share
apt-get install nautilus-wallpaper
apt-get install ncurses-base
apt-get install ncurses-bin
apt-get install ndisgtk
apt-get install ndiswrapper-common
apt-get install ndiswrapper-utils-1.9
apt-get install net-tools
apt-get install netbase
apt-get install netcat
apt-get install netcat-traditional
apt-get install network-manager
apt-get install network-manager-gnome
apt-get install notify-osd
apt-get install ntfs-3g
apt-get install ntfsprogs
apt-get install ntpdate
apt-get install nvidia-173-modaliases
apt-get install nvidia-180-modaliases
apt-get install nvidia-71-modaliases
apt-get install nvidia-96-modaliases
apt-get install nvidia-common
apt-get install obex-data-server
apt-get install odbcinst1debian1
apt-get install onboard
apt-get install openoffice.org-base
apt-get install openoffice.org-base-core
apt-get install openoffice.org-calc
apt-get install openoffice.org-common
apt-get install openoffice.org-core
apt-get install openoffice.org-draw
apt-get install openoffice.org-emailmerge
apt-get install openoffice.org-gnome
apt-get install openoffice.org-gtk
apt-get install openoffice.org-help-en-gb
apt-get install openoffice.org-help-en-us
apt-get install openoffice.org-hyphenation
apt-get install openoffice.org-hyphenation-en-us
apt-get install openoffice.org-impress
apt-get install openoffice.org-java-common
apt-get install openoffice.org-l10n-common
apt-get install openoffice.org-l10n-en-gb
apt-get install openoffice.org-l10n-en-za
apt-get install openoffice.org-math
apt-get install openoffice.org-style-human
apt-get install openoffice.org-thesaurus-en-au
apt-get install openoffice.org-thesaurus-en-us
apt-get install openoffice.org-writer
apt-get install openprinting-ppds
apt-get install openssh-client
apt-get install openssl
apt-get install orbit2
apt-get install padevchooser
apt-get install paman
apt-get install paprefs
apt-get install parted
apt-get install passwd
apt-get install patch
apt-get install pavucontrol
apt-get install pavumeter
apt-get install pciutils
apt-get install pcmciautils
apt-get install perl
apt-get install perl-base
apt-get install perl-modules
apt-get install phonon
apt-get install phonon-backend-gstreamer
apt-get install pidgin
apt-get install pidgin-data
apt-get install pidgin-libnotify
apt-get install pidgin-otr
apt-get install pkg-config
apt-get install pm-utils
apt-get install pnm2ppa
apt-get install po-debconf
apt-get install policykit
apt-get install policykit-gnome
apt-get install poppler-utils
apt-get install popularity-contest
apt-get install powermgmt-base
apt-get install ppp
apt-get install pppconfig
apt-get install pppoe
apt-get install pppoeconf
apt-get install procps
apt-get install psfontmgr
apt-get install psmisc
apt-get install pulseaudio
apt-get install pulseaudio-esound-compat
apt-get install pulseaudio-module-gconf
apt-get install pulseaudio-module-hal
apt-get install pulseaudio-module-x11
apt-get install pulseaudio-module-zeroconf
apt-get install pulseaudio-utils
apt-get install pxljr
apt-get install python
apt-get install python-apport
apt-get install python-apt
apt-get install python-beagle
apt-get install python-brlapi
apt-get install python-cairo
apt-get install python-central
apt-get install python-compizconfig
apt-get install python-crypto
apt-get install python-cups
apt-get install python-cupshelpers
apt-get install python-dbus
apt-get install python-debian
apt-get install python-dev
apt-get install python-fstab
apt-get install python-gconf
apt-get install python-gdata
apt-get install python-gdbm
apt-get install python-glade2
apt-get install python-gmenu
apt-get install python-gnome2
apt-get install python-gnome2-desktop
apt-get install python-gnomecanvas
apt-get install python-gnupginterface
apt-get install python-gobject
apt-get install python-gst0.10
apt-get install python-gtk2
apt-get install python-gtkhtml2
apt-get install python-gtksourceview2
apt-get install python-imaging
apt-get install python-launchpad-bugs
apt-get install python-launchpad-integration
apt-get install python-libxml2
apt-get install python-minimal
apt-get install python-newt
apt-get install python-notify
apt-get install python-paramiko
apt-get install python-pexpect
apt-get install python-pkg-resources
apt-get install python-problem-report
apt-get install python-pyatspi
apt-get install python-pymad
apt-get install python-pyorbit
apt-get install python-rdflib
apt-get install python-smbc
apt-get install python-support
apt-get install python-uno
apt-get install python-usb
apt-get install python-virtkey
apt-get install python-vte
apt-get install python-xapian
apt-get install python-xdg
apt-get install python-xkit
apt-get install python2.6
apt-get install python2.6-dev
apt-get install python2.6-minimal
apt-get install qt-creator
apt-get install qt4-qmake
apt-get install qt4-qtconfig
apt-get install radeontool
apt-get install raptor-utils
apt-get install rarian-compat
apt-get install rdate
apt-get install rdesktop
apt-get install readahead
apt-get install readline-common
apt-get install reiserfsprogs
apt-get install rhythmbox
apt-get install rss-glx
apt-get install rsync
apt-get install samba
apt-get install samba-common
apt-get install sane-utils
apt-get install scim
apt-get install scim-bridge-agent
apt-get install scim-bridge-client-gtk
apt-get install scim-gtk2-immodule
apt-get install scim-modules-socket
apt-get install screen
apt-get install screen-profiles
apt-get install screen-resolution-extra
apt-get install seahorse
apt-get install seahorse-plugins
apt-get install sed
apt-get install setserial
apt-get install sg3-utils
apt-get install sgml-base
apt-get install sgml-data
apt-get install shared-mime-info
apt-get install simple-ccsm
apt-get install smartdimmer
apt-get install smbclient
apt-get install smpeg-gtv
apt-get install smpeg-plaympeg
apt-get install splix
apt-get install ssh-askpass-gnome
apt-get install ssl-cert
apt-get install startup-tasks
apt-get install strace
apt-get install subversion
apt-get install sudo
apt-get install sun-java6-bin
apt-get install sun-java6-jre
apt-get install sun-java6-plugin
apt-get install synaptic
apt-get install sysklogd
apt-get install syslinux
apt-get install system-config-printer-common
apt-get install system-config-printer-gnome
apt-get install system-services
apt-get install system-tools-backends
apt-get install sysv-rc
apt-get install sysvinit-utils
apt-get install tar
apt-get install tasksel
apt-get install tasksel-data
apt-get install tcl8.4
apt-get install tcpd
apt-get install tcpdump
apt-get install telnet
apt-get install thunderbird
apt-get install thunderbird-locale-en-gb
apt-get install time
apt-get install tomboy
apt-get install toolame
apt-get install toshset
apt-get install totem
apt-get install totem-common
apt-get install totem-gstreamer
apt-get install totem-mozilla
apt-get install totem-plugins
apt-get install totem-xine
apt-get install transmission-common
apt-get install transmission-gtk
apt-get install ttf-arphic-ukai
apt-get install ttf-bitstream-vera
apt-get install ttf-dejavu
apt-get install ttf-dejavu-core
apt-get install ttf-dejavu-extra
apt-get install ttf-freefont
apt-get install ttf-liberation
apt-get install ttf-opensymbol
apt-get install ttf-sazanami-gothic
apt-get install ttf-unfonts-extra
apt-get install twolame
apt-get install tzdata
apt-get install ubuntu-keyring
apt-get install ubuntu-minimal
apt-get install ubuntu-sounds
apt-get install ubuntu-standard
apt-get install ubuntu-system-service
apt-get install ucf
apt-get install udev
apt-get install ufw
apt-get install unattended-upgrades
apt-get install unixodbc
apt-get install uno-libs3
apt-get install unrar
apt-get install unshield
apt-get install unzip
apt-get install update-inetd
apt-get install update-manager-core
apt-get install update-motd
apt-get install update-notifier-common
apt-get install upstart
apt-get install upstart-compat-sysv
apt-get install upstart-logd
apt-get install ure
apt-get install usbutils
apt-get install usplash
apt-get install usplash-theme-mint
apt-get install util-linux
apt-get install uuid-runtime
apt-get install vbetool
apt-get install vdr
apt-get install vdr-plugin-xineliboutput
apt-get install vim
apt-get install vim-common
apt-get install vim-gnome
apt-get install vim-gui-common
apt-get install vim-runtime
apt-get install vim-tiny
apt-get install vino
apt-get install vlc
apt-get install vlc-data
apt-get install vlc-nox
apt-get install vorbis-tools
apt-get install w32codecs
apt-get install w3m
apt-get install wamerican
apt-get install wbritish
apt-get install wget
apt-get install whiptail
apt-get install whois
apt-get install wireless-crda
apt-get install wireless-tools
apt-get install wodim
apt-get install wpasupplicant
apt-get install x-ttcidfont-conf
apt-get install x11-apps
apt-get install x11-common
apt-get install x11-session-utils
apt-get install x11-utils
apt-get install x11-xfs-utils
apt-get install x11-xkb-utils
apt-get install x11-xserver-utils
apt-get install x11proto-composite-dev
apt-get install x11proto-core-dev
apt-get install x11proto-damage-dev
apt-get install x11proto-fixes-dev
apt-get install x11proto-input-dev
apt-get install x11proto-kb-dev
apt-get install x11proto-randr-dev
apt-get install x11proto-render-dev
apt-get install x11proto-video-dev
apt-get install x11proto-xext-dev
apt-get install x11proto-xf86vidmode-dev
apt-get install x11proto-xinerama-dev
apt-get install x264
apt-get install xauth
apt-get install xbase-clients
apt-get install xbitmaps
apt-get install xchat
apt-get install xchat-common
apt-get install xdg-user-dirs
apt-get install xdg-user-dirs-gtk
apt-get install xdg-utils
apt-get install xfonts-100dpi
apt-get install xfonts-75dpi
apt-get install xfonts-base
apt-get install xfonts-encodings
apt-get install xfonts-scalable
apt-get install xfonts-utils
apt-get install xfsprogs
apt-get install xineliboutput-sxfe
apt-get install xinit
apt-get install xinput
apt-get install xkb-data
apt-get install xml-core
apt-get install xmms2-core
apt-get install xmms2-plugin-id3v2
apt-get install xmms2-plugin-mad
apt-get install xorg
apt-get install xscreensaver-data
apt-get install xscreensaver-gl
apt-get install xserver-common
apt-get install xserver-xorg
apt-get install xserver-xorg-core
apt-get install xserver-xorg-input-all
apt-get install xserver-xorg-input-evdev
apt-get install xserver-xorg-input-kbd
apt-get install xserver-xorg-input-mouse
apt-get install xserver-xorg-input-synaptics
apt-get install xserver-xorg-input-wacom
apt-get install xserver-xorg-video-all
apt-get install xserver-xorg-video-apm
apt-get install xserver-xorg-video-ark
apt-get install xserver-xorg-video-ati
apt-get install xserver-xorg-video-chips
apt-get install xserver-xorg-video-cirrus
apt-get install xserver-xorg-video-fbdev
apt-get install xserver-xorg-video-geode
apt-get install xserver-xorg-video-i128
apt-get install xserver-xorg-video-i740
apt-get install xserver-xorg-video-intel
apt-get install xserver-xorg-video-mach64
apt-get install xserver-xorg-video-mga
apt-get install xserver-xorg-video-neomagic
apt-get install xserver-xorg-video-nv
apt-get install xserver-xorg-video-openchrome
apt-get install xserver-xorg-video-r128
apt-get install xserver-xorg-video-radeon
apt-get install xserver-xorg-video-rendition
apt-get install xserver-xorg-video-s3
apt-get install xserver-xorg-video-s3virge
apt-get install xserver-xorg-video-savage
apt-get install xserver-xorg-video-siliconmotion
apt-get install xserver-xorg-video-sis
apt-get install xserver-xorg-video-sisusb
apt-get install xserver-xorg-video-tdfx
apt-get install xserver-xorg-video-trident
apt-get install xserver-xorg-video-tseng
apt-get install xserver-xorg-video-v4l
apt-get install xserver-xorg-video-vesa
apt-get install xserver-xorg-video-vmware
apt-get install xserver-xorg-video-voodoo
apt-get install xsltproc
apt-get install xterm
apt-get install xtrans-dev
apt-get install xulrunner-1.9
apt-get install xulrunner-1.9-gnome-support
apt-get install xvattr
apt-get install xvidcap
apt-get install xviewg
apt-get install xzgv
apt-get install yelp
apt-get install zenity
apt-get install zip
apt-get install zlib1g
apt-get install zlib1g-dev
