CXX_FLAGS=-std=c++0x -Wall -Werror -Wextra -I/opt/local/include -L/opt/local/lib -I/usr/local/include -L/usr/local/lib -lPocoFoundation -lPocoNet -lPocoZip

all:
	g++ -o unzipurl ${CXX_FLAGS} main.cpp
