all:
	PATH="/Users/francis/bin:/opt/local/bin:/usr/local/bin:/Users/francis/Qt/5.3.0/clang_64/bin:/Users/francis/programming/projects/stacked-crooked/bin:/Users/francis/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin" g++-4.9 -std=c++11 -O3 -g0 -Wall -Wextra -Werror -pedantic -pthread main.cpp -L/opt/local/lib -isystem /opt/local/include -ltbb
