######################################################################
# Automatically generated by qmake (2.01a) za 23. dec 00:22:15 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += E:/Development/Qt/Editor
INCLUDEPATH += E:/Development/Qt/Editor

QT += network

HEADERS += Plugin.h

SOURCES += main.cpp \
           Plugin.cpp

