all:
	g++ -std=c++11 -ggdb3 -O1 -Wall -Wextra -Werror -pedantic -isystem /opt/local/include -pthread main.cpp -ltbb /root/boost_1_54_0/stage/lib/libboost_filesystem.a /root/boost_1_54_0/stage/lib/libboost_system.a
	./a.out
