#!/bin/sh

### BEGIN INIT INFO
# Provides:          HighScoreServer
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

case "$1" in
  start)
    echo "Starting HighScoreServer"
    /usr/bin/HighScoreServer 1>&2 2>/var/log/hsslog &
    ;;
  stop)
    echo "Stopping HighScoreServer"
    kill $(pgrep HighScoreServer)
    ;;
  *)
    echo "Usage: /etc/init.d/webserver {start|stop}"
    exit 1
    ;;
esac

exit 0
