" -----------------------------------------------------------------------------
"  General Settings
" -----------------------------------------------------------------------------

" Show line numbers
set number

" Paste doesn't indent or do funny stuff
set paste

" Add common search paths
set path+=/usr/local/include,/opt/local/include

" Enable most intuitive backspace behavior
set bs=2

" Expand tabs to spaces
set expandtab

" Don't replace tabs with spaces in makefiles
autocmd FileType make set noexpandtab

" Set tabs to 4 spaces
set softtabstop=4 
set tabstop=4 
set shiftwidth=4

" Colorize search results
set hlsearch 

" Show search results while typing
set incsearch

" Set auto-indent rules
set autoindent

" Set filetype dependent indention rules
filetype plugin indent on

" Disable annoying backup/swap files
set nobackup
set noswapfile
set nowritebackup 

" Turn off vi compatibility
set nocompatible

" Show the ruler at the bottom
set ruler

" Show nice title in xterm
set title

" Set ignore case when searching using only lower case characters
set ignorecase
set smartcase

" Enable syntax coloring
syntax enable
syntax on

" Set the color scheme
colorscheme torte


" -----------------------------------------------------------------------------
"  File types
" -----------------------------------------------------------------------------


" -----------------------------------------------------------------------------
" Key mappings
" -----------------------------------------------------------------------------
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
set splitbelow
set splitright

" Disable Ex mode (bastard!)
:map Q <Nop>

" Yank until end of line
map Y y$


fun! OpenFileBrowser()
    let file = expand("%:t")
    :Ve
    exec ":normal 1G/^" . file . "\n"
endf


" Toggle between absolute and relative line numbers
function! NumberToggle()
  if(&relativenumber == 1)
    set number
  else
    set relativenumber
  endif
endfunc

nnoremap <C-n> :call NumberToggle()<cr>
"au FocusLost * :set number
"au FocusGained * :set relativenumber
"autocmd InsertEnter * :set number
"autocmd InsertLeave * :set relativenumber



:map <F1> :NERDTreeToggle<CR>
:map <F2> :tab split<CR>
:map <F3> :NERDTreeFind<CR>


" -----------------------------------------------------------------------------
" OpenFile. Modelled after the Firefox "Open Link in New Tab"-command.
" -----------------------------------------------------------------------------
fun! OpenFile()
  let tab_id = expand("%")
  tab split
  tabmove
  normal gf
  while tab_id != expand("%")
    tabprev
  endw
  normal j
endf

" Map CTRL-G to the OpenFile function
:map <C-G> :call OpenFile()<CR>


" -----------------------------------------------------------------------------
" Vundle settings
" -----------------------------------------------------------------------------
set nocompatible               " be iMproved
filetype off                   " required!

set rtp+=~/.vim/bundle/vundle
call vundle#rc()

Bundle 'gmarik/vundle'
Bundle 'Align'
Bundle 'NERD_tree-Project'

filetype plugin indent on

