
all:
	g++ -o test -O0 -ggdb3 -Wall -Wextra -Werror -pedantic-errors main.cpp
	g++ -o teststdout -O0 -ggdb3 -Wall -Wextra -Werror -pedantic-errors teststdout.cpp
	g++ -o teststderr -O0 -ggdb3 -Wall -Wextra -Werror -pedantic-errors teststderr.cpp
