FLAGS = -O0 -std=c++0x -ggdb3 -Wall -Wextra -Werror -pedantic-errors
all:
	g++ -o test ${FLAGS} main.cpp
	g++ -o teststdout ${FLAGS} teststdout.cpp
	g++ -o teststderr ${FLAGS} teststderr.cpp
	g++ -o testwritefile ${FLAGS} testwritefile.cpp
