#!/bin/sh
if [ $# -ne 1 ] ; then
    echo "Usage: `basename $0` {arg}"
    exit 65
fi

for File in "$@" ; do
    astyle  --indent=spaces=4 --brackets=break --indent-switches --indent-namespaces --indent-labels --indent-preprocessor --indent-col1-comments --max-instatement-indent=80 --pad-header --unpad-paren --convert-tabs --align-pointer=middle --suffix=none --lineend=windows --recursive $File
done
