#!/bin/bash
# Subversion passes $6 as HEAD file and $7 as modified file.
if [[ "`uname`" == 'Darwin' ]]; then
    /Developer/Applications/Utilities/FileMerge.app/Contents/MacOS/FileMerge -left `pwd`/$6 -right `pwd`/$7
else
    meld $6 $7
fi

