all:
	g++ -std=c++11 -O2 -g -Wall -Wextra -pedantic -pthread main.cpp -o cond -Wno-deprecated-declarations
	#g++ -DSEMAPHORE -std=c++11 -O2 -g -Wall -Wextra -pedantic -pthread main.cpp -o sema -Wno-deprecated-declarations

