#!/bin/bash
set -x
set -e
name="$(date +%s)"
dir="$HOME/tmp/${name}"
cp -r $HOME/programming/googlecode/stacked-crooked/Playground/cppgen_template "${dir}" #use your own dir
cd "$dir"
xdg-open  "cppgen_template.creator"
