all:
	g++ -std=c++11 -O2 -Wall -pedantic -pthread blocking_tcp_echo_client.cpp -o blocking_tcp_echo_client -lboost_system
	g++ -std=c++11 -O2 -Wall -pedantic -pthread blocking_tcp_echo_server.cpp -o blocking_tcp_echo_server -lboost_system
