keycode  14 = parenleft 5 braceleft bracketleft
keycode  20 = parenright degree braceright bracketright
keycode  51 = dead_grave sterling
keycode 49 = less greater
keycode 94 = at numbersign
add mod3 = Mode_switch
keycode 64 = Mode_switch
keysym l = l L L bar
keysym n = n N dead_tilde
keysym colon = colon slash backslash
