all:
	g++-4.8 -std=c++11 -O2 -Wall -Wextra -Werror -pedantic -isystem /opt/local/include -L/opt/local/lib -pthread main.cpp -ltbb /Volumes/Users/francis/Development/programming/projects/ps_backup/ps/lib/boost/Darwin/x86_64/libboost_filesystem.a /Volumes/Users/francis/Development/programming/projects/ps_backup/ps/lib/boost/Darwin/x86_64/libboost_system.a
	./a.out
